//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2020MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BB2020Entities : DbContext
    {
        public BB2020Entities()
            : base("name=BB2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Races_Players> Races_Players { get; set; }
        public virtual DbSet<Races_Players_Skills> Races_Players_Skills { get; set; }
        public virtual DbSet<Races_Players_SkillTypes> Races_Players_SkillTypes { get; set; }
        public virtual DbSet<Races_SpecialRules> Races_SpecialRules { get; set; }
        public virtual DbSet<Rules_InjuryTypes> Rules_InjuryTypes { get; set; }
        public virtual DbSet<Rules_LvlType> Rules_LvlType { get; set; }
        public virtual DbSet<Rules_Skills_FSkills> Rules_Skills_FSkills { get; set; }
        public virtual DbSet<Rules_Skills_List> Rules_Skills_List { get; set; }
        public virtual DbSet<Rules_Skills_Types> Rules_Skills_Types { get; set; }
        public virtual DbSet<Rules_SpecialRules> Rules_SpecialRules { get; set; }
        public virtual DbSet<User_Rosters> User_Rosters { get; set; }
        public virtual DbSet<User_Rosters_Injury> User_Rosters_Injury { get; set; }
        public virtual DbSet<User_Rosters_LvlTypes> User_Rosters_LvlTypes { get; set; }
        public virtual DbSet<User_Rosters_Players> User_Rosters_Players { get; set; }
        public virtual DbSet<User_Rosters_Skills> User_Rosters_Skills { get; set; }
    }
}
