//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2020MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Races_SpecialRules
    {
        public int RSRID { get; set; }
        public int SRID { get; set; }
        public int RaceID { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Rules_SpecialRules Rules_SpecialRules { get; set; }
    }
}
