//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2020MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Races_Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Races_Players()
        {
            this.Races_Players_Skills = new HashSet<Races_Players_Skills>();
            this.Races_Players_SkillTypes = new HashSet<Races_Players_SkillTypes>();
            this.User_Rosters_Players = new HashSet<User_Rosters_Players>();
        }
    
        public int PlayerID { get; set; }
        public int RaceID { get; set; }
        public int MA { get; set; }
        public int AG { get; set; }
        public int AV { get; set; }
        public Nullable<int> PA { get; set; }
        public int Cost { get; set; }
        public int ST { get; set; }
        public string Name { get; set; }
        public int MaxQTY { get; set; }
    
        public virtual Race Race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Races_Players_Skills> Races_Players_Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Races_Players_SkillTypes> Races_Players_SkillTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Rosters_Players> User_Rosters_Players { get; set; }
    }
}
