//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2020MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules_Skills_FSkills
    {
        public int ForbiddenID { get; set; }
        public int SkillID { get; set; }
        public int FSkillID { get; set; }
    
        public virtual Rules_Skills_List Rules_Skills_List { get; set; }
        public virtual Rules_Skills_List Rules_Skills_List1 { get; set; }
    }
}
