//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2020MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Rosters_Injury
    {
        public int RInjuryID { get; set; }
        public int RPlayerID { get; set; }
        public int InjuryID { get; set; }
    
        public virtual Rules_InjuryTypes Rules_InjuryTypes { get; set; }
        public virtual User_Rosters_Players User_Rosters_Players { get; set; }
    }
}
